### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by KseniiaCheloshkina** [kotikkonstantin/ru-autopunctuation#3]
I'm trying to run inference using different functions from inference.py
```python
    MODEL_HYPERPARAMETERS = prepare_hyperparameters()
    bert_punc, tokenizer = model_and_tokenizer_initialize(DEVICE, MODEL_HYPERPARAMETERS)
```
The second line fails becaise it searches for file `checkpoints\echomsk6000\20210430_125222_rubert-base-cased-sentence_segment_size_16_stacked_hidden_states_concat_4_mean_sent_agg\model` to load weights into the model and can't find it in this path. Could you please provide the weights?

**Comment by kotikkonstantin** [comment]
@KseniiaCheloshkina https://drive.google.com/file/d/1uQ2GvM28EwkPczbBiAwmZLBoxnTnRNrc/view?usp=sharing
